### ISSUE TITLE
Embedded video redirects

### ISSUE THREAD

**Issue by quantumfx** [cs-nero/Youtter#1]
One of the main draws of the [Invidition](https://addons.mozilla.org/en-US/firefox/addon/invidition/) Youtube->Invidious redirect addon is the support for embedded Youtube videos. Would be a great feature for Youtter as well!

**Comment by cs-nero** [comment]
Will look into either at the weekend or next week! Thanks!

**Comment by cs-nero** [comment]
Hello @quantumfx , 

I looked into the feature, but it is not possible yet because the direct url of a Yotter video can look like: 
https://yotter.xyz/videoplayback?expire=1607816987&ei=uwLVX9fDBpqqx_APvKyRkAk&ip=2a03%3A4000%3A6%3A246a%3A1420%3Af8ff%3Afefa%3A94f1&id=o-AOluXCdMtIZqWsra796i_oRl8HyA-50-EF9zTj48n-zu&itag=18&source=youtube&requiressl=yes&mh=qM&mm=31%2C29&mn=sn-5oxmp55u-8pxe%2Csn-4g5ednsl&ms=au%2Crdu&mv=m&mvi=1&pl=32&initcwndbps=961250&vprv=1&mime=video%2Fmp4&ns=YVI9j5taKdZdYgahkr3nN4AF&gir=yes&clen=22827053&ratebypass=yes&dur=284.583&lmt=1592848192631767&mt=1607795077&fvip=4&c=WEB&txp=6216222&n=rx_8ctKj9B-Ue4ZQe&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIwWGaHg6ZP-WgjndUnNSxzgUiwh3PBp6sHqjl81YcGxAiA4K5i0AS4Zur-kf_HbmWl--LUpbd-CFUJPlGMlYlwhPw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgCvtUxH4_U5FwkTQYI0D8JeSPgNEhWpDKxJbMyBcTgNACIBL6jydP_uxjaOL8-Pic0gSNbShrFulrJdM602yMY0Ph&host=r1---sn-5oxmp55u-8pxe.googlevideo.com

This link is only available, when someone logged in with his account -> right click on the video -> "Show video" or "Copy video url".
It is impossible to get a logical url out there which I can forward. Maybe, this can be made when you no longer need to register on yotter. 
I tried to forward the whole page of yotter (for example https://yotter.xyz/watch?v=LwT94AP7zg4) but there are many problems with setting cookies on an embedded frame because of CSP and the SameSite-attribute. 

Here is a screenshot of the error trying to forward the video from duckduckgo.com and after trying to login (only german): https://imgur.com/a/frwJjP9 

I am in connection with the developer of yotter and will ask if we could do anything. 
I will write here again when I got something.

**Comment by cs-nero** [comment]
@quantumfx Released a new update with the option to block embedded youtube videos as long as there is no forwarding possible. You can then open the video by clicking the title.
